spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${CI_DB_HOST}:${CI_DB_PORT}/${CI_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8mb4
    username: ${CI_DB_USER}
    password: ${CI_DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: false

  security:
    jwt:
      secret: ${CI_JWT_SECRET}
      access-token-expiration-msec: 900000
      refresh-token-expiration-msec: 1209600000
app:
  kakao:
    rest-api-key: ${CI_KAKAO_KEY}
    token-uri: https://kauth.kakao.com/oauth/token
    user-me-uri: https://kapi.kakao.com/v2/user/me
    redirect-uris:
      - "kakao9ec4a4d46982a8f4d7b19fcc7099c63c://oauth"


cloud:
  aws:
    region:
      static: ${CI_AWS_REGION}
    s3:
      bucket: ${CI_AWS_BUCKET}